version: '3.8'
services:
  mymovies-api:
    container_name: mymovies-api
    image: mymovies
    ports:
      - "8080:80"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - sqlServer
    networks:
      - backend
  sqlServer:
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Database2023!"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "MoviesDb"
    ports:
      - "1433:1433"
    networks:
      - backend
  mymovies-web:
    container_name: mymovies-web
    image: movies-frontend
    ports:
      - "8081:8080"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  backend:
    driver: bridge